- package.json
- src/App.jsx
- src/components/Footer.jsx
- src/components/NotFoundPage.jsx
- src/constants/defaults.js
- src/pages/individual/PictureBook.jsx
- src/pages/report/BulkReport.jsx
- src/pages/report/ReportSightings.jsx
- src/pages/report/StandardReport.jsx
- The layout on the report sightings page is not pixel perfect to what it was before.
- I had to change the way the photo credit on the 404 page displayed because, after changing the layout for the transitions, it displayed on top of the footer. The way it is right now, it should always display over the picture, but not always within the initial screen view.
> transitions

- package.json
When running npm install:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: react@16.14.0
npm ERR! node_modules/react
npm ERR!   react@"^16.8.6" from the root project
npm ERR!   peer react@">=16.3.0" from @emotion/core@10.1.1
npm ERR!   node_modules/@emotion/core
npm ERR!     dev @emotion/core@"^10.0.14" from the root project
npm ERR!     peer @emotion/core@"^10.0.27" from @emotion/styled@10.0.27
npm ERR!     node_modules/@emotion/styled
npm ERR!       dev @emotion/styled@"^10.0.14" from the root project
npm ERR!     2 more (emotion-theming, @emotion/styled-base)
npm ERR!   26 more (@emotion/styled, @flatfile/react, react-dom, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^17.0.0" from …
```
> Pin @material-ui/utils version to 5.0.0-alpha.27

- src/constants/apiKeysTemplate.js
`apiKeysTemplate.js` was removed in commit
"DEX-337 create AlertWrapper component" (86226532) and it was probably a
mistake (not explained in commit message).  Add the file back because it
is necessary for the build.
> Add src/constants/apiKeysTemplate.js back

- .github/workflows/update-submodule.yml
The github action should run every time develop is updated and updates the `_frontend` submodule in houston to the latest develop of codex-frontend.
A [PAT token](https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/creating-a-personal-access-token) needs to be generated with "repo" permissions and then added as a repository secret "PAT_TOKEN" on codex-frontend "settings" -> "secrets" page.
I tried this workflow in my forked repo and it created this [commit](https://github.com/WildMeOrg/houston/commit/3f2f2e0016471930d066b48c5a3329138cdd6049):
```diff
commit 3f2f2e0016471930d066b48c5a3329138cdd6049 (origin/update-frontend)
Author: github-actions <github-actions@github.com>
Date:   Wed Sep 1 21:18:36 2021 +0000
Update _frontend to latest develop …
```
> Add github workflow to update houston _frontend submodule

- .github/workflows/update-submodule.yml
The submodule path was changed from `_frontend` to `_frontend.codex`
late in Oct 2021. This change fixes the workflow so that the houston
submodule is kept in sync with the tip of `codex-frontend@develop`.
> Fix houston update workflow

- src/components/fields/edit/LatLongEditor.jsx
Fixes a bug where LatLng input would not show its initial value
> Show initial value in latlng input

- src/components/fields/edit/LocationIdEditor.jsx
- src/pages/fieldManagement/settings/defaultFieldComponents/Editors.jsx
- src/pages/fieldManagement/settings/defaultFieldComponents/TreeEditor.jsx
Fixes a couple of bugs:
- Selecting a subregion was throwing an error on the report form page (`cannot read property "id" of undefined`)
- Dropdown options were changing after selecting a region 
Added an optimization so that choices are not recursively collapsed every render
> Fix region editor

- .gitignore
- config/webpack/webpack.common.js
- package.json
- src/pages/serverStatus/ServerStatus.jsx
For Houston integration this depends on https://github.com/WildMeOrg/houston/pull/506 It will need merged before this gets merged.
In the example screenshot, the version and commit are the same. Once we've created a tag for this repo it will display something like `<tag>[-<commit-distance>-g<hash>[-dirty]]`. For example, `v1.2.3-14-g0bc163f-dirty` where `v1.2.3` was the latest tag, there are `14` commits since the last tag, current hash is `0bc163f`, and there are currently uncommitted files in the repo indicated by `-dirty`.
> Display version

- src/components/TextContainers.jsx
- src/components/report/TermsAndConditionsDialog.jsx
- src/pages/bulkImport/BulkReportForm.jsx
- src/pages/reportSighting/ReportForm.jsx
- src/pages/reportSighting/ReportSighting.jsx
- Removes the terms and conditions checkbox for authorized users:
- Removes all terms and conditions logic from the `BulkReportForm` because that form is only visible to authorized users.
- Updates logic to conditionally require the terms and conditions acknowledgment in the `ReportForm`.
- Replaces the temporary terms and conditions text with the actual copy.
**Potential issue**: On some screen sizes, it is not obvious that the Codex Terms of Use continue beyond the bottom of the visible dialog:
> DEX-802 remove terms and conditions for authorized users

- locale/en.json
- src/components/AuthenticatedAppHeader/NotificationsPane.jsx
- src/components/AuthenticatedAppHeader/index.js
- src/components/dialogs/NotificationDetailsDialog.jsx
- src/constants/notificationSchema.js
- src/models/notification/usePatchNotification.js
- src/pages/assetGroup/AssetGroup.jsx
- src/pages/notifications/Notifications.jsx
- src/utils/notificationUtils.js
Responds to all of JH's QA feedback from https://wildme.atlassian.net/browse/DEX-663:
> In the Notifications modal, clicking “Mark as Read” can cause notifications to disappear or change their button to a grayed out DONE.
Per discussions with Ben, all notifications have a view button, but some of these view buttons navigate the user to their home page, while others pull up a dialog with actions.
> "Mark as Read” button can change size depending on length of text next to it:
In the process of troubleshooting this, I kind of accidentally added a <div> around the button. This coincidentally seems to force a standardization of button size. If someone who understands css better than me know why this happened, I would be eager to know that.
> In “View All Notifications”, clicking on an entry …
> Dex 663 qa feedback and DEX-808

- src/AuthenticatedSwitch.jsx
- src/UnauthenticatedSwitch.jsx
- src/pages/reportSighting/ReportForm.jsx
- src/pages/reportSighting/Success.jsx
- After successfully POSTing a sighting, an unauthenticated user is redirected to `/report/success` rather than to the pending sighting page that they are not authorized to see.
- Because only unauthorized users see the Success page, I removed it from the AuthenticatedSwitch, and removed the authorization conditions within the Success component.
> DEX-811 missing "report sighting success" page

- src/pages/sighting/AssetGroupSighting.jsx
- Adds the current hash to the redirect URL after a successful AGS commit so that the user stays on the same tab they were on when they committed the AGS.
> DEX-847 remain on tab after committing AGS

- src/models/individual/useFilterIndividuals.js
- src/models/individual/useQueryIndividuals.js
With the addition of Elasticsearch to houston in wildmeorg/houston#521, the `/api/v1/search/individuals` endpoint no longer exists. Eventually, we should use the new endpoint, `/api/v1/individuals/search`. However, that will also require changes to the request and response. So, for now, I am changing to `/api/v1/search/proxy/individuals`, which should function exactly the same as `/api/v1/search/individuals`.
> update individual search API endpoints

- package.json
- src/components/AuthenticatedAppHeader/NotificationsPane.jsx
- src/components/ButtonLink.jsx
- src/components/UserProfile.jsx
- src/components/cards/Card.jsx
- src/components/cards/CollaborationsCard.jsx
- src/constants/notificationSchema.js
Addresses JH's QA feedback for DEX-803:
> Following up on our Slack conversation. I think all that is left is the make the notifications for a collaboration link to the collaboration table when the “View” button is clicked.
I tried to follow Emily's pattern from her recent PR and use useLocation. I don't think that it fit exactly my use case.
Instead, I followed some online advice(https://dev.to/gedalyakrycer/5-remarkable-react-router-features-anchor-links-query-params-more-2aeg#anchorLinks and https://stackoverflow.com/questions/40280369/use-anchors-with-react-router) and added the 'react-router-hash-link' package.
Slightly added to the ButtonLink component to make the use of HashLinks from within buttons easier going forward.
> DEX-803 make view buttons go to collaboration table directly

- src/components/cards/collaborations/collaborationStates.js
- src/components/dialogs/notificationDialogUtils/NotificationCollaborationEditRequestDialog.jsx
- src/components/dialogs/notificationDialogUtils/NotificationCollaborationRequestDialog.jsx
- src/components/dialogs/notificationDialogUtils/NotificationIndividualMergeRequestDialog.jsx
Back end standardized all "declined" patches, etc. to "denied". Confirmed that it doesn't work the old way and works this new way.
> change front end to reflect back end change from declined to denied

- locale/en.json
- src/models/individual/useIndividualFieldSchemas.js
- src/models/individual/usePatchIndividual.js
- src/pages/individual/EditIndividualMetadata.jsx
- src/pages/individual/Individual.jsx
- src/pages/sighting/encounters/CreateIndividualModal.jsx
- src/utils/nameUtils.js
- On the individuals page, reads the metadata values on the metadata card.
- Enables editing of the individual metadata. If the individual does not have a nickname, and none is added, the nickname is not sent as part of the PATCH request.
- Adds validation for required fields to the edit individual metadata form. 
- Removes status as a default field. After discussion, it was decided that users can add it as a custom field if they want to track status. 
I left the names as defaultName/Name and nickname/Nickname(s) for now.
> DEX-720 edit individual metadata default fields

- src/pages/individual/EditIndividualMetadata.jsx
Updating an existing name was resulting in an error. Because the incorrect schema names were being passed to `deriveNameGuid`, no guids were found, and the operation in the PATCH request to houston was being set as "add" instead of "replace". This bug was introduced in #294. 
As a part of the fix, I looked into simplifying the request to only use replace and send a guid if it didn't already exist. However, houston throws an exception if the guid in the request does not match an existing name.
https://github.com/WildMeOrg/houston/blob/1ce45296747b4d3becd1f794e8e25053c80f0f33/app/modules/individuals/parameters.py#L210-L216
> DEX-862 fix individual name update

- src/pages/sighting/encounters/EditEncounterMetadata.jsx
- Adds the customFields object to the PATCH request when submitting edits to an encounter's metadata.
- Adds validation for required fields, both custom and default.
> DEX-745 encounter metadata - edit custom fields

- locale/en.json
- src/pages/individual/EditIndividualMetadata.jsx
- Enables custom field editing for individuals, including validation of required fields.
- Resets the EditIndividualMetadata form values when the cancel or close buttons are clicked.
- Updates the close button callback so that the behavior is the same whether the cancel button or the close button is clicked.
- Removes a duplicate entry from `locale/en.json`
> DEX-721 individual metadata custom fields

- src/components/Button.jsx
- src/components/Link.jsx
- src/components/ResponsiveText.jsx
- src/components/Text.jsx
- src/components/cards/EncountersCard.jsx
- src/components/dataDisplays/DataDisplay.jsx
- src/components/dataDisplays/cellRenderers/CapitalizedStringRenderer.jsx
- src/components/dataDisplays/cellRenderers/DateRenderer.jsx
- src/components/dataDisplays/cellRenderers/DefaultRenderer.jsx
- src/components/dataDisplays/cellRenderers/LocationRenderer.jsx
- src/components/dataDisplays/cellRenderers/OverflowController.jsx
- src/components/dataDisplays/cellRenderers/SpecifiedTimeRenderer.jsx
- src/components/dataDisplays/cellRenderers/UserRenderer.jsx
- src/hooks/useActionsColumnWidth.js
This prevents the individual's sightings table cells from wrapping. When a cell's text overflows and a user hovers over the cell, a tooltip appears with the full cell value. For cells that have not overflowed, there is no tooltip.
I updated all of the cell renderers instead of just the ones used by the EncountersCard in order to ensure that this design would work for them.
Hiding overflow required a sacrifice of the automatic table layout. For this table, I chose to let the Date column take a percentage of the space, let the Actions column take a fixed, calculated amount of space, and let the Location and Owner columns split the rest.
The actions cells do not have a `white-space: nowrap` style applied. However, they should not wrap because the calculation mentioned above should always …
> DEX 845 - cleanup encounters table wrapping

- src/App.jsx
- src/index.jsx
- Adds comments about react-hot-loader being safe to use in a non-production environment.
- Moves react-hot-reloader's `hot` usage from `index` to `App` because of this warning:
> DEX-944 - limit hot reloader to development environment

- locale/en.json
- src/pages/bulkImport/BulkReportForm.jsx
- src/pages/bulkImport/constants/bulkReportConstants.js
- src/pages/bulkImport/utils/prepareAssetGroup.js
- src/pages/bulkImport/utils/useBulkImportFields.js
- Uses `assetReferences` as the key for assets in the bulk import workflow, which restores "Assets" to the available sighting fields list.
- Uses `firstName` as the key for individual names in the bulk import workflow, which restores "Individual Name" to the available animal fields list. I checked with BE and the key `firstName` on the `encounter` is the contract that is expected.
- Adds the sighting `comments` key to the bulkImportCategories sighting fields so that "Notes" correctly appears in the available sighting fields lists. Because it is possible for sighting comments to conflict in the spreadsheet entries, only the last comment that has a value for a given sighting is persisted to the sighting.
- The last `time` and `timeSpecificity` for a given sighting are saved to that sighting …
> DEX-939 restore missing bulk import fields

- src/components/dataDisplays/cellRenderers/OverflowController.jsx
This reverts commit a6ded5a10ae99474c9f5c2c45dd4fb75034012f3: "Remove width of 100% from noWrapStyles"
- This style is required for LocationRenderer when lat and long exist
After this fix, the render controllers display like this. "Location renderer (detail)" is the one with latitude and longitude
> DEX-845 fix location render overflow

- src/pages/bulkImport/BulkReportForm.jsx
- Moves FlatfileButton `devMode` and `managed` props into the settings prop so that they work correctly.
- `devMode` causes a banner to display at the top of the dialog.
- `managed` adds additional file options. When managed is false, the file options are limited to .csv, .tsv, and .txt spreadsheets
- Sets devMode to true or false conditionally based on the `__DEV__` global variable.
- Removes the `maxRecords` prop instead of moving it to settings. Currently it is unknown how many encounters houston can handle, and the bulk import processing implementation is changing.
> DEX-945 update Flatfile props

- src/pages/bulkImport/BulkFieldBreakdown.jsx
- src/pages/bulkImport/constants/bulkReportConstants.js
- src/pages/bulkImport/utils/prepareAssetGroup.js
- src/pages/bulkImport/utils/useBulkImportFields.js
This fixes two issues for custom fields used in bulk upload:
- It sets the Flatfile field key to a value that indicates if it is a setting or encounter field and includes the guid. I used `guid` instead of `name` because `name` is not necessarily unique for custom fields. The category type is required so that it can be parsed during data processing in order to assign the custom field to the correct category.
- It adds the custom fields to the sightings and encounters during data processing.
- For a sighting, the custom fields that will be used are the values from the last row for that sighting that has any value for a custom sighting field.
For example, if you have the following spreadsheet, the sighting will have one custom field, "custom sighting field 2" with a value of "value 4"
| …
> DEX-940 bulk import custom field updates

- src/hooks/useFetch.js
This is a quick fix to prevent the report page rendering in a React loop.
> Prevent useFetch setError when status is loading

- src/components/AnnotationCreator.jsx
Fixes the issue where if an annotation-less encounter already exists, a new encounter was being created anyway with the new manual annotation assigned to the latter.
With the fix, a new encounter is not created if an annotation-less encounter already exists, and the new manual annotation is assigned to the already-existing one instead. Only in the !pending case, of course.
> Dex 975 fill animal1 with manual annotation if none

- locale/en.json
- src/components/UserProfile.jsx
- src/constants/intelligentAgentSchema.js
- src/models/users/useUserMetadataSchemas.js
- src/pages/generalSettings/GeneralSettings.jsx
- src/pages/generalSettings/IntelligentAgentSettings.jsx
schema.getValue → schema?.getValue in a few places, because it was breaking as soon as the user had a twitter handle but the twitterbot was disabled.
Added new data to the intelligentAgentSchema pertaining to user metadata.
Improved the setShowTwitterSuccess logic to be more robust to differences in the twitterStatusCode output vs the twitterTestResults output (and yes, the do disagree sometimes, resulting e.g. in situations where the status code is 400 but the test results still show success as true).
Added keys to IntelligentAgentSettings to make the warnings go away.
> Dex 937 twitter handle user data

- src/pages/sighting/MoreAnnotationMenu.jsx
Not removing the whole UI because I expect this functionality to be restored soon
> Disable kickoff annotation UI

- src/hooks/useReportUppyInstance.js
Uppy/Tus (via tus-js-client) saves a fingerprint to local storage so that an interrupted file upload can be resumed. 
Removing the fingerprint after a successful upload will prevent the extra HEAD requests from being made, failing, and displaying in the console.
> dex-1058 remove uppy/tus local fingerprint

- package.json
- src/components/settings/MediaViewer.jsx
- src/hooks/useReportUppyInstance.js
- Sends a delete request when a file is removed from the Uppy dashboard on the Report a Sighting or Bulk Import page.
- Updates the `uuid` package in order to get access to the new `validate` function
- If there is an error with the deletion, the error message is logged to the console. I had originally alerted the user to the error, but decided against it because there is no recovery action that they can take, and when we submit the sighting we only include the asset references stored in client memory.
The houston changes for this functionality are in wildmeorg/houston#631
> dex 989 - send delete request for removed file

- src/components/cards/MetadataCard.jsx
- src/utils/fieldUtils.js
Default values for custom fields were not being displayed. Now, they are:
> Dex 665 show default custom values

- src/pages/setup/SiteSetup.jsx
- src/pages/sighting/SightingCore.jsx
- src/pages/sighting/SightingEntityHeader.jsx
- Comments out the sighting history dialog to hide it from users while it is still using mock data.
- Replaces the dolphin image on the site setup page with Bao.
| before | after |
| ---       | ---    |
| <img width="604" alt="before" src="https://user-images.githubusercontent.com/50299119/170741058-6a2514bf-8488-425f-8e45-3a5a1eafb164.png"> | <img width="536" alt="after" src="https://user-images.githubusercontent.com/50299119/170741082-b923aa00-e737-48c4-88e8-144f5aadb81d.png">
> Cleanup placeholders - sighting history and site setup

- src/components/cards/EncountersCard.jsx
- src/models/sighting/useRunIdOnSighting.js
- src/pages/sighting/SightingEntityHeader.jsx
- src/pages/sighting/encounters/Encounters.jsx
- src/pages/sighting/identification/RerunIdentificationDialog.jsx
This PR adds the button to re-run identification on a sighting, but I am not seeing the any changes to the pipeline_status property after a successful POST to `/api/v1/sightings/8be7d16b-eb8f-4b6f-bec4-54d3daca0394/rerun_id`. Since Howard is out I wonder if someone else can look into it, maybe @naknomum or @bluemellophone?
> Send re-run Id request

- locale/en.json
- src/models/assetGroup/useAssetGroup.js
- src/pages/assetGroup/AGSTable.jsx
- src/pages/assetGroup/AssetGroup.jsx
- src/pages/sighting/SightingCore.jsx
- src/pages/sighting/SightingEntityHeader.jsx
- Bulk import page
- Adds polling for the asset group while image processing is in progress so that the UI can change when processing is complete.
- Adds a simple image processing alert indicating that image processing is in progress and that some functionality is not available.
- Sets the asset counts in the table to "pending".
- Pending sighting page
- Adds the same basic image processing alert.
- Hides all of the tabs while image processing is in progress.
- Uses a Material UI Skeleton instead of a featured photo while image processing is in progress.
- Changes how the `activeTab` is calculated so that it is only ever a valid value.
These changes span both DEX-1083 and DEX-967
-----
*Please ignore the status card being incorrect on the sighting page. This will be fixed in #362*
> Basic image processing handling

- src/components/dataDisplays/CollapsibleRow.jsx
- src/pages/userManagement/UserEditTable.jsx
Fixes issue where the action icons would not be right-justified after filtering in the user edit table:
> Dex 477 right align filtered icons

- locale/en.json
- src/pages/match/MatchCandidatesTable.jsx
- src/pages/match/QueryAnnotationsTable.jsx
Ticket recommendations:
- Rename “Annotation” to “Candidate Rank”
- Rename “Match candidates” to “Candidate Annotations”
- Remove “C” from match candidate listings
- View Sighting column no longer sortable
Note that "Candidate Annotations" instead of Candidate annotations" seems to go against a style choice that Ben has  made app-wide, so I kept as, "Candidate annotations".
Also changed the Q1 to just 1 on the query table after a chat with Tanya about it.
> Dex 929 follow up

- src/hooks/useFetch.js
- src/models/site/useGetTwitterbotTestResults.js
- src/pages/generalSettings/GeneralSettings.jsx
This PR fixes the issue where useGetTwitterbotTestResults was being called despite having disabled passed to it as a queryOption.
I tried a number of things such as using enabled instead of disabled as the query option. These did not solve the issue (at least, they were not sufficient to solve the issue). However, I ended up using fewer double negatives in the codebase, so I decided to keep using enabled.
What I believe was the issue was gleaned from [this page](https://github.com/TanStack/query/issues/1196):
> Maybe you were setting enabled to a falsy value rather than really setting it to false ? This is a breaking change in v3 (stated here: https://react-query-beta.tanstack.com/guides/migrating-to-react-query-3#queryoptionsenabled). Falsy values will no longer work, it needs to really …
> Dex 1091 quieter twitterbot

- .github/workflows/build.yml
- .gitignore
- README.md
- src/components/fields/edit/mapUtils/LatLngMap.jsx
- src/components/fields/filter/mapUtils/AreaMap.jsx
- src/components/filterFields/mapUtils/PointDistanceMap.jsx
- src/components/inputs/mapUtils/AreaMap.jsx
- src/components/inputs/mapUtils/LatLngMap.jsx
- src/components/maps/MultiplePoints.jsx
- src/components/maps/SinglePoint.jsx
- src/constants/apiKeysTemplate.js
- src/hooks/useGoogleMapsApiKey.js
- src/index.jsx
- src/pages/bulkImport/BulkReportForm.jsx
- Remove apiKeysTemplate.js
- Change code to use site settings instead of apiKeys
- The settings are `googleMapsApiKey`, `flatfileKey` and `sentryDsn`
- Use `fetch` to get the sentry dsn and move react render App into the `finally` handler
See WildMeOrg/houston#665
> Use site settings instead of apiKeys.js

- locale/en.json
- src/pages/assetGroup/AssetGroup.jsx
- Adds an error alert message.
- Adds an indeterminate progress bar to the in progress alert so that the page gives a slightly better impression that it is doing something.
- eventually there will be metrics included in the alert and the progress bar will probably move into the alert too. This is a quick, intermediary change that hopefully improves the user experience slightly.
- A large bulk import will show the in progress state naturally. You can force that state by stopping all of your celery containers.
- To force the error state:
- stop your celery containers
- add something that will error to the first line of the set function
https://github.com/WildMeOrg/houston/blob/a3dba0dd4804c1439aae90bc1ca08cc3896e5eac/app/modules/progress/models.py#L419
- start your celery containers
> dex 1083 - improved preparation state feedback for bulk import 

- locale/en.json
- src/components/AuthenticatedAppHeader/NotificationsPane.jsx
- src/components/dialogs/notificationDialogUtils/NotificationCollaborationDeniedDialog.jsx
- src/components/dialogs/notificationDialogUtils/index.js
- src/constants/notificationSchema.js
- src/pages/notifications/Notifications.jsx
Adds a notificationAvatar to each notification schema to indicate which variable from NotificationUtils's getNotificationProps to use for gettin the first letter as an Avatar stand-in. 
Also fixes a bug that we missed earlier when collaboration_revoked was changed to collaboration_denied.
QA notes:
Here's what it looked like before (Note all of the "U"s as the avatar):
Here's what is looks like after the fix:
Note that there's about an hour's worth of state built up on unacceptablebehavior.org right now if you log in as user1@example.com with the default password, so you don't have to reproduce all of these notifications yourself.
collaboration_denied and
collaboration_revoke
are both accommodated now.
See Jerome Jerome The Metronome and Betty pictured below:
> Dex 1119 notification placeholder improvement

- src/pages/splash/Metrics.jsx
- Updates the hard coded metrics to the current values on zebra.wildme.org:
-  Identified Individuals - the number of individuals
- Reported Sightings - the number of asset group sightings plus the number of migrated sightings (sightings without asset group sighting GUIDs)
- Users - the number of users that are not `internal` an do not have an `@localhost` email address
- Adds `FormattedNumber` so that the counts are formatted.
**NOTE**: This is a temporary fix until these values can be accessed via houston.
> dex-1178 Update landing page metrics to current zebra values

- src/pages/sighting/encounters/AddAnnotationsDialog.jsx
- src/pages/sighting/encounters/MoveAnnotationDialog.jsx
Just a bug fix that I found along the way and was a quick fix.
QA notes: view-only collaborators shouldn't be able to do EDITy things on another user's sighting. But they _should_ be able to dismiss the dialog box telling them as much:
> fix clearError bug in AddAnnotationsDialog.jsx

- src/pages/sighting/encounters/Encounters.jsx
- src/pages/sighting/statusCard/StatusCard.jsx
- src/pages/sighting/statusCard/TimelineStep.jsx
When match results are not yet ready, clicking "view identification results" from the "Animal" tab's encounter(s) takes the user to the overview tab, where they can see that ID is still in progress/failed.
When match results are ready, the same button takes the user directly to the match results page.
JH mentioned casually in my 1:1 today that ideally he'd want the click to navigate directly to focus on the identification step.
I tried a few things to this effect (e.g., https://github.com/WildMeOrg/codex-frontend/pull/390/commits/d4fe72ca7f900d3d1b7c90b357b86d0b35345e21 and https://github.com/WildMeOrg/codex-frontend/pull/390/commits/1821b907f73cc185099602a2755a55dd90965880), and none of them seemed to work. Open to suggestions.
I'm gonna leave the domId in there even though I didn't end …
> Dex 1196 id results before available fix

- src/pages/match/MatchSighting.jsx
- Prevents a row from rendering for the match results if the `annotation_data` for the `/id_result` response does not include the annotation.
- hot spotter includes results for annotations that houston has filtered out because they are not associated with an encounter.
> dex 1027 - filter out match results without annotations

- locale/en.json
- src/pages/sighting/encounters/Encounters.jsx
- src/pages/sighting/statusCard/StatusCard.jsx
- src/pages/sighting/statusCard/TimelineStep.jsx
- Redefines a "complete" status so that "failed" is no longer a sub-state of "complete"
- Internationalizes "View Match Results" button.
- Adds an alert within the timeline step if the step has failed.
This is related to WildMeOrg/houston#693
> dex 1121 - pipeline status improvements

- locale/en.json
- src/pages/sighting/SightingCore.jsx
The sighting UI uses the minimal, overview only layout while Sighting Preparation is in progress. However, if the preparation stage fails, the full layout is used and the alert displays the incorrect information.
- Updates the logic to use the minimal layout until the preparation stage is complete.
- Updates the alert title so that it makes sense for both the inProgress and failed states.
- This is currently how the alert works when detection fails.
| in progress | error |
| :---: | :---: |
| <img width="982" alt="alert-in-progress" src="https://user-images.githubusercontent.com/50299119/176755145-fb5f3093-9bf7-469b-9de0-1ad079b1917d.png"> | <img width="982" alt="alert-error" src="https://user-images.githubusercontent.com/50299119/176755167-66f5db87-f3ce-4143-ac68-e …
> dex 967 - fix sighting UI when preparation fails

- locale/en.json
- src/components/Button.jsx
- src/pages/fieldManagement/settings/saveField/OptionEditor.jsx
- N/A
- N/A
This PR removes the unneccesary id attribute from custom filed options. This brings newly-created custom field options in line with the current behavior of migrated custom fields. 
The removal of id here does not seem to affect the metadata cards for sightings or encounters.
It was decided that, because the end users will be exporting, bulk importing, and otherwise using these custom field options, they should be in control of what both the labels and values are (provided that these are unique - see DEX-1270 for that issue).
Before deleting "Standing":
After deleting "Standing":
(i.e., they would all be removed)
Before deleting "Standing":
After deleting "Standing":
Other things to confirm:
> DEX-1270 remove id from optionEditor

- docs/contribution-guide.md
- docs/release-procedure.md
> begin release procedure

- src/components/BannerLogo.jsx
- N/A
- N/A
DEX-1176 (the issue was the the header title in zebra codex was wrapping in small screen sizes).
I'm not certain of the best way to handle very long codex names, but adding a min-width of a reasonable length seemed to fix the issue at hand. Ignore not-quite-suitable branch name.
> DEX-1176 add minWidth

- src/utils/useItisSearch.js
ItisIdSearch has historically been finicky and taken too long to perform.
The timeout has been extended to 1 minute.
Note/warning: I could not reproduce any difficulty with the ITIS Id search. The results were near-instantaneous for me.
This was true even when I turned wifi off on my machine. And when I used a private browser session. And when I cleared the cache.
I am not sure how to reproduce the historic issue, but I suspect that my one code change would do the trick in extending the timeout should it ever need it??
NA
NA
DEX-1314
> DEX-1314 extend itisIdSearch timeout to 1 min.

- locale/en.json
- src/pages/fieldManagement/settings/defaultFieldComponents/SpeciesEditor.jsx
- src/utils/useItisSearch.js
If the end user is searching for a species to add to their codex instance, historically the potentially long search time for this and unreliability of the API has been a suboptimal user experience.
This PR introduces the following features:
1. After 5 seconds, if the search status is still loading and there's no error, the user will see an indication that the search is still underway:
2. If the search errors out in any way, instead of whichever, if any, error message that would have been issued by the response, the end user will now see:
3. The end user will be able to search again, and either the error alert or the search status ("Still generating list...") will be dismissed.
4. The end user will not see either of these indicators if the search is faster than 5 seconds:
5. The end user …
> Dex 1313 add timeout user guidance

- docs/contribution-guide.md
Contact information was outdated; needs to go to a general location rather than a specific email
> Generalize contact information

- src/pages/generalSettings/GeneralSettings.jsx
1. when user clicks at next button, all changes will be saved
2. if user sets "allow twitter submissions" to true, but don't fill in required fields, next button on that page will be disabled
> next button also saves changes

- src/pages/individual/EditIndividualMetadata.jsx
- src/pages/sighting/EditSightingMetadata.jsx
- src/pages/sighting/encounters/EditEncounterMetadata.jsx
hotfix for #523 
#523 
by adding default value assignment, prevent program from throwing error when there is no custom fields in individual/sighting/encounter category.
> hotfix of issue 523

- locale/en.json
- src/pages/createIndividual/CreateIndividual.jsx
- src/pages/match/MatchSighting.jsx
add an info box on create individual page about codex ID
adjust the "CONFIRM MATCH" button's border radius to get aligned with other buttons
> autogen-create-individual-page

- src/components/UserManagerCollaborationEditTable.jsx
- src/pages/changeLog/ChangeLog.jsx
when change log table cell content overflows, wrap the data
> wrap table cell

- locale/en.json
- src/components/dataDisplays/ElasticsearchSightingsDisplay.jsx
- src/components/filterFields/OptionTermFilter.jsx
- src/components/filterFields/useBuildFilter.js
- src/models/individual/useIndividualSearchSchemas.js
- src/models/sighting/useSightingSearchSchemas.js
1. now user can search sightings by encounter species/sex/custom fields.
2. abstract logic about checking the type/filter of custom fields to a hook and reuse the hook in sightings/encounters/individuals search schemas
3. fix a lint error about nesting ternary expressions
4. comment out some code about displaying encounter images count and individual info on sightings search page, because currently we don't have that in BE returned data
covers issue #555
> 555-sighting-encounter-search

- .github/workflows/update-submodule.yml
> Update the codex-frontend module reference to Houston project

- src/pages/sighting/AnnotationDetail.jsx
- src/pages/sighting/Annotations.jsx
- src/pages/sighting/MoreAnnotationMenu.jsx
- src/pages/sighting/SightingCore.jsx
- src/pages/sighting/SightingEntityHeader.jsx
sightings metadata page:
1. remove photograph tab
2. on annotations tab, display images with or without annotations
3. add "add annotations" button to the 3dot button
4. when click at an image that has no annotations, "add tag" is hidden, we can't add tag to image that has no annotation
> sightings metadata redesign

- locale/en.json
- src/components/dialogs/ReviewSighting.jsx
add 'unprocessed' status for uncommitted sightings on sightings page, the button will be disabled if the sighting is not committed.
> match-status-patch

- src/pages/sighting/identification/CommitDialog.jsx
- src/pages/sighting/identification/CustomMatchingSetForm.jsx
- src/pages/sighting/identification/RerunIdentificationDialog.jsx
- src/pages/sighting/identification/buildMatchingSetQuery.js
on sightings "re-run identification" page and and "commit sighting custom identification" page, when select a top level region, its sub regions will be all included.
> 503-nested-regions

- locale/en.json
- src/components/dataDisplays/ElasticsearchSightingsDisplay.jsx
- src/models/sighting/useSightingSearchSchemas.js
1. add column number_of_animals/freeform_location/number_of_encounters to sightings table
2. add filter number_of_individuals to sightings search schema, now user can search by number of individuals
> 564-565-566-sightings-table-and-search

- src/pages/match/MatchSighting.jsx
increase confirm match button zIndex so that it won't be blocked by table header
> increase confirm match button zIndex

- src/components/fields/edit/LocationIdEditor.jsx
- src/components/fields/edit/TreeViewComponent.jsx
- src/components/fields/edit/TreeViewDemo.jsx
1. remodel region editor, UI looks different
2. now when user reports sighting and select region, the dropdown list is a tree view, we can see all regions and sub regions in tree structure
3. when selecting top level region, its sub regions will be expanded
4. when searching region, all regions includes the search text will be displayed, user can also expand the top region to see its sub regions, even if the sub regions don't match search text
5. this component is also used on "re-run identification" page and "customize identification" page
6. on the two pages above, it is still not multiple selection, but we will run job with the selected region and its sub regions, a previous ticket implemented this feature, not affected by this ticket.
> Region editor remodel

- locale/en.json
- src/AuthenticatedSwitch.jsx
- src/components/fields/edit/LocationIdEditor.jsx
- src/components/fields/edit/TreeViewComponent.jsx
- src/pages/fieldManagement/RegionManagement.jsx
- src/pages/fieldManagement/settings/DefaultFieldTable.jsx
- src/pages/fieldManagement/settings/defaultFieldComponents/TreeEditor.jsx
region administration:
- change the region editor from a modal to a page
- update layout, add finish and cancel button
- add a checkbox in front of every region: user can select and deselect any region and save
- when creating sighting/re-run identification, deselected regions will be disabled and can't be chosen
> region administration

- .github/workflows/build_codex_fe.yml
- .github/workflows/build_houston_fe.yml
docker builds cannot be successful from forks, so that check will be skipped unless pr is from main repo. slack notifications are no longer used and not needed
> check management and slack notif
