WildMeOrg/codex-frontend

- locale/en.json
- src/components/Button.jsx
- src/components/Footer.jsx
- src/components/ResponsiveHeader.jsx
- src/pages/splash/HelpAsk.jsx
- src/pages/splash/Metrics.jsx
- src/pages/splash/Social.jsx
- src/pages/splash/Splash.jsx
- src/pages/splash/Testimonial.jsx
- src/pages/splash/Trifold.jsx
- src/styles/materialTheme.js
This should get the splash page pretty much in line with the design Mads provided. No attempt to make it look good on mobile, want to get this approved first (basically merging so I can deploy)
> Splash page theme adjustments

- src/components/ResponsiveText.jsx
- src/pages/splash/HelpAsk.jsx
- src/pages/splash/HowItWorks.jsx
- src/pages/splash/Metrics.jsx
- src/pages/splash/Social.jsx
- src/pages/splash/Splash.jsx
- src/pages/splash/Testimonial.jsx
- src/pages/splash/Trifold.jsx
(mobile compatible splash page)
> Responsive text errwhere

- src/components/AvatarGallery.jsx
- src/components/BigAvatar.jsx
- src/components/ConfirmDelete.jsx
- src/components/DividerTitle.jsx
- src/components/EncounterCard.jsx
- src/components/EntityCard.jsx
- src/components/FilterPanel.jsx
- src/components/Footer.jsx
- src/components/SearchFilterList.jsx
- src/components/SimpleFormPage.jsx
- src/components/UserProfile.jsx
- src/modules/users/selectors.jsx
- src/pages/administration/components/SummaryCard.jsx
- src/pages/report/TermsAndConditionsDialog.jsx
> Add admin badge

- .github/workflows/build.yml
Build the package in as a continuous activity of development.
> Build the package nightly, on push and conditional on pull request

- locale/en.json
- src/components/EditUserMetadata.jsx
- src/models/users/usePatchUser.js
- src/models/users/useUserMetadataSchemas.js
> Password verification before editing email

- src/components/Footer.jsx
I am dumb. This is an easy fix where pixel number changes and that's it.
> DEX-374 tweak based on tanya feedback for better behavior

- locale/en.json
- src/components/fields/edit/SelectionEditor.jsx
- src/models/sighting/useSightingFieldSchemas.js
> Build species detector model multiselect

- locale/en.json
- src/components/UserProfile.jsx
- src/components/cards/GpsCard.jsx
- src/components/cards/SightingsCard.jsx
- src/components/dataDisplays/DataDisplay.jsx
- src/components/maps/SinglePoint.js
- src/pages/sighting/MapInSighting.jsx
- remove extra border around map 
- change table size to match collaborations table 
- include link to sighting in table
> Improve sightings table

- locale/en.json
- src/components/cards/SightingsCard.jsx
- src/components/fields/view/SelectViewer.jsx
- src/models/assetGroupSighting/usePatchAssetGroupSighting.js
- src/models/sighting/useSightingFieldSchemas.js
- src/pages/sighting/EditSightingMetadata.jsx
- src/pages/sighting/OverviewContent.jsx
- src/pages/sighting/Sighting.jsx
- src/pages/sighting/StatusCard.jsx
This PR makes it possible to patch assetGroupSighting top-level metadata fields. It also does a few more things I will note in the comments
> Patch AGS properties

- src/AuthenticatedSwitch.jsx
- src/constants/queryKeys.js
- src/models/auditLogs/useGetAuditLogs.js
- src/models/users/useGetMe.js
- src/pages/devTools/AuditLog.jsx
Quick lil audit log UI for debugging porpoises
> Create audit log UI

- locale/en.json
- src/components/EntityHeaderNew.jsx
- src/components/UserProfile.jsx
- src/pages/assetGroup/AssetGroup.jsx
- src/pages/sighting/Sighting.jsx
> Move tabs to within entity header, improve look and feel

- src/models/site/useDeleteSiteSettingsMedia.js
- src/models/site/useDetectionConfig.js
- src/models/site/useGetSiteInfo.js
- src/models/site/usePostSettingsAsset.js
- src/models/site/usePutSiteSettings.js
- src/models/site/useRemoveCustomField.js
- src/models/site/useSiteSettings.js
Updated the URLS used in codex to reflect changes in DEX 674. 
Testing is using the frontend to create a new site, update the logo (a file), checking site info and creating a new sighting
> 674 codex frontend changes

- src/components/ProfileUploader.jsx
- src/components/report/UploadManager.jsx
- src/components/settings/SettingsFileUpload.jsx
- src/hooks/useReportUppyInstance.js
@bluemellophone new endpoint works thanks!
> Tus route change

- src/pages/sighting/encounters/Encounters.jsx
Problem was sighting properties were not getting copied to new encounters so table had the wrong data.
> Fix individual sightings table

- src/pages/sighting/encounters/AnnotationsCard.jsx
> Fix annotation card scroll

- src/components/AnnotationCreator.jsx
- src/models/annotation/usePostAnnotation.js
The problem was that for annotation creation, the dialog is full screen, so the alert was popping up in a part of the dialog that it shouldn't have been.
> Dex 863 z indexing of alerts

- src/AuthenticatedSwitch.jsx
- src/pages/bulkImport/BulkReportForm.jsx
- src/pages/bulkImport/utils/useBulkImportFields.js
- src/pages/bulkImport/utils/validateIndividualNames.js
- src/pages/bulkImport/utils/validateMinMax.js
Individual found:
Individual not found:
> Flatfile names

- README.md
- src/components/AuthenticatedAppHeader/IndividualsButton.jsx
- src/components/AuthenticatedAppHeader/SightingsButton.jsx
- src/hooks/useFetch.js
- src/models/individual/useIndividualTermQuery.js
- src/models/sighting/useSightingTermQuery.js
This works regardless of `-` characters and should be more efficient than the old way too
> Fix guid search on individuals and sightings

- src/models/assetGroupSighting/useAddAnnotationsToAGSEncounter.js
- src/models/encounter/useAddAnnotationsToSightingEncounter.js
- src/pages/sighting/encounters/AddAnnotationsDialog.jsx
- src/pages/sighting/encounters/MoveAnnotationDialog.jsx
Another brick in the wall for DEX-766. Failing to refresh the sighting/AGS was pretty jarring in the UI so I wanted to get to this one ASAP
> Migrate hooks for adding annotations to encounters

- src/pages/individual/Individual.jsx
Doesn't look like this API will exist in time for MVP, so we are just going to comment out the table for now.
> Remove fake cooccurrences table

- locale/en.json
- src/components/AuthenticatedAppHeader/IndividualsButton.jsx
- src/components/IndividualSelector.jsx
- src/components/UserProfile.jsx
- src/components/dataDisplays/DataDisplay.jsx
- src/components/dataDisplays/IndividualsDisplay.jsx
- src/components/dataDisplays/Paginator.jsx
- src/components/dataDisplays/SightingsDisplay.jsx
- src/components/dataDisplays/cellRenderers/DateRenderer.jsx
- src/components/dataDisplays/cellRenderers/SpeciesRenderer.jsx
- src/components/dataDisplays/cellRenderers/index.js
- src/components/filterFields/IntegerFilter.jsx
- src/components/filterFields/OptionTermFilter.jsx
- src/hooks/useOptions.js
- src/models/individual/useFilterIndividuals.js
- src/models/individual/useIndividualSearchSchemas.js
- src/models/sighting/useFilterSightings.js
- src/models/sighting/useSightingSearchSchemas.js
- src/pages/individual/SearchIndividuals.jsx
- src/pages/sighting/SearchSightings.jsx
I set the limit for both pages to 100 search results
> Pagination and sorting for search pages 

- src/components/bulkImport/UnprocessedBulkImportAlert.jsx
- src/pages/assetGroup/AGSTable.jsx
- updates asset group sightings in the useAssetGroup response to use the new schema from wildmeorg/houston#631
> DEX-1045 - Update to new AGS schema

- src/components/IndividualSelector.jsx
- src/components/cards/RelationshipsCard.jsx
- src/pages/individual/MergeDialog.jsx
- src/pages/sighting/encounters/ManuallyAssignModal.jsx
> Do not allow merge of an individual with itself

- src/pages/bulkImport/utils/useBulkImportFields.js
Emily caught some bugs where things don't work as expected if  #duplicateFields !== 1.
This should fix those issues.
> Dex 1034 bug fixes

- locale/en.json
- src/components/fields/edit/SelectionEditor.jsx
This in conjunction with https://github.com/WildMeOrg/codex-frontend/pull/356 fixes the bug where users couldn't edit custom multi-select fields.
This current PR fixes the specific bug where the first option could not be created.
> Dex 1005 fix multi select custom field edit

- locale/en.json
- src/AuthenticatedSwitch.jsx
- src/UnauthenticatedSwitch.jsx
- src/components/SimpleFormPage.jsx
- src/pages/auth/EmailVerified.jsx
> Email verification page 

- src/models/users/useGetUserSightings.js
This is the front-end update for the back-end fix in WildMeOrg/houston#718. It does not have its own bug number, but is related to DEX-1201.
> update useGetUserSightings query type to term

- .github/workflows/nightly.yml
- prod/build-n-push.sh
This is a step in the direction of automating the image build.
Right now it will build the `wildme/codex-frontend:dev` image every night.
> Automate the image build

- locale/en.json
- src/components/dataDisplays/Paginator.jsx
- src/pages/individual/Individual.jsx
-----
- Internationalization: I think I internationalized everything in `Paginator.jsx` because it is a small module. I only internationalized the text in `Individuals.jsx` that was closely related to the `no-unsafe-optional-chaining` errors.
- Linter errors: I left some linter errors in `Individuals.jsx` because they are being addressed in #407.
> eslint fixes - no-unsafe-optional-chaining

- src/UnauthenticatedSwitch.jsx
- src/models/auth/useLogin.js
- src/pages/auth/Login.jsx
> Send search params and hash with login url

- .github/pull_request_template.md
> add JIRA and or github issue association

- src/components/cards/CollaborationsCard.jsx
- src/components/dataDisplays/DataDisplay.jsx
- N/A
- N/A
- N/A
DEX-922
This follows up on JH's QA feedback that the Popper was buried beneath the stickyHeader.
After a lot of unnecessary other steps, I ended up just ramping up the z-index of the Popper. I predict that this is not best practice, but am happy to be wrong about this. 
I don't know what the alternative could be for Popper. Due to aforementioned unnecessary other steps, I happen to have a [minimal reproducible example](https://stackblitz.com/edit/react-wzniay?file=demo.tsx) handy in case we want to collectively ask SO about best practice with this …
> 922 follow up

- package.json
- scripts/printUnusedKeys.js
303 keys were identified as potentially unused, though I think some of them are required to translate data coming from houston (the `CONFIGURATION_` ones).
Here's the script output:
```
ben@BScheiner-MBP16 codex-frontend % npm run print-unused-keys
> codex-frontend@1.0.2 print-unused-keys
> node ./scripts/printUnusedKeys.js
FYI, this script takes forever to run! Recommendation is to leave it running overnight or in the background.
"ADMINISTRATION" may be unused.
"ENCOUNTERS" may be unused.
"REMOVE_FROM_CLUSTER" may be unused.
"REMOVE_ANNOTATION_FROM_CLUSTER" may be unused.
"REMOVE_ANNOTATION_FROM_CLUSTER_CONFIRMATION" may be unused.
"CONFIGURATION_EMAIL_SERVICE_LABEL" may be unused.
"CONFIGURATION_EMAIL_SERVICE_DESCRIPTION" may be unused.
"CONFIGURATION_EMAIL_SERVICE_PASSWORD_LABEL" may …
```
> Script for printing unused translation keys

- src/pages/siteStatus/SiteStatus.jsx
- NA
- NA
DEX-1433
Pretty self explanatory. Site status now looks like:
> DEX-1433 remove EDM build date and commit hash from Site Status page

- package.json
> Update package version to 1.1.0

- docs/release-procedure.md
> add clarification about type of merge into main

- src/pages/reportSighting/ReportSighting.jsx
> Fix cdx-11 "Documentation links in product are broken"

- src/models/individual/useIndividualFieldSchemas.js
- src/pages/individual/EditIndividualMetadata.jsx
1. Add a field schema "species"
2. List all site species as options, provides both the scientific and the common names
3. Add it on "edit individual metadata" page, and make it required.
> cdx-7 add species on edit individual metadata page

- src/components/fields/edit/SelectionEditor.jsx
Fix some required dropdown fields showing two * in label name issue.
> cdx-47 two stars issue

- src/pages/bulkImport/BulkImport.jsx
wild me documentation website url changed; needs to be updated in the product as well. Discovered during QA of Codex 2.0 dev cycle
> Update photo optimization link

- locale/en.json
Twitter account needs to be Basic paid account
> Update en.json with Twitter account requirement

- locale/en.json
- src/components/UppyDashboard.jsx
- src/components/report/ReportSightingsPage.jsx
- src/models/assetGroup/usePostAssetGroup.js
- src/pages/bulkImport/BulkImport.jsx
- src/pages/home/ProfileSetup.jsx
- src/pages/reportSighting/ReportForm.jsx
- src/pages/reportSighting/ReportSighting.jsx
- src/pages/reportSighting/ReportSightingBreadcrumbs.jsx
on Report a sighting page:
1. add a breadcrumb
2. add a progress bar
3. adjust size of upload window
4. adjust buttons
5. update href of photoGuidlineUrl
6. put all required fields on the second step of reporting a sighting
7. put all optional fields on the third step of reporting
8. add Back button
9. add Skip and submit button
10. add recaptcha
11. change Login link from a page to a modal
> cdx-25/26/27/28/29/30/31

- locale/en.json
- src/components/cards/MetadataCard.jsx
- src/components/fields/edit/DateEditor.jsx
- src/components/fields/view/DateRangeViewer.jsx
- src/hooks/useMutate.js
- src/models/individual/usePatchIndividual.js
- src/models/sighting/usePatchSighting.js
- src/pages/fieldManagement/settings/saveField/CheckDateRangeIntegrity.js
- src/pages/fieldManagement/settings/saveField/SaveField.jsx
- src/pages/individual/EditIndividualMetadata.jsx
- src/pages/sighting/EditSightingMetadata.jsx
- src/pages/sighting/encounters/EditEncounterMetadata.jsx
- src/utils/fieldUtils.js
- src/utils/formatters.js
Fix date picker/date range custom fields won't save issue on individual/sighting/encounter metadate editing page
> cdx-15-fix-date-custom-fields-issue

- locale/en.json
- src/AuthenticatedSwitch.jsx
- src/models/users/useGetRequests.js
- src/models/users/usePostRequestInvitation.js
- src/pages/auth/RequestInvitation.jsx
- src/pages/generalSettings/GeneralSettings.jsx
- src/pages/setup/Requests.jsx
On Request an invitation page, 
1. when user fill in required email address and name and click SEND REQUEST button, send POST request to /api/v1/account-requests
2. at the same time send recaptcha token
3. deal with response status, if status is 200, show successful page, if error, show error message
Create a new page:  /requests/ to display requests from invitation page
1. Send GET method to BE and get response
2. display requests list on the page
> Account request

- locale/en.json
- src/pages/reportSighting/ReportForm.jsx
1. Add a translation for label "INVITATION_REQUESTS" which got lost during merging
2. On report a sighting page, move required encounter fields to 'required data' page
3. Update required fields check function
> cdx-26-patch

- src/pages/reportSighting/ReportForm.jsx
when report a sighting, encounter fields should only show up when user selects "one animal"
> cdx-26-patch-2

- locale/en.json
- src/App.jsx
- src/components/inputs/ColorInput.jsx
- src/styles/materialTheme.js
1. update theme primary colors
2. update black color in theme
3. add secondary and tertiary text color in theme
> cdx-56-update-theme-color-and-text-color

- src/components/AuthenticatedAppHeader/SearchButton.jsx
- src/components/Button.jsx
- src/styles/materialTheme.js
1. update all buttons' border radius
2. update secondary buttons' variant and text color
3. update tertiary buttons' text color to reflect theme color
4. buttons allow just text, just icons, icon before text, and text before icon
> cdx-57-update-button-styles

- src/App.jsx
- src/pages/changeLog/ChangeLog.jsx
fix the flashing setup page issue. when data is still loading, show the loading screen, not the initiation page.
> fix the flashing setup page issue

- locale/en.json
- src/components/dataDisplays/IndividualsDisplay.jsx
on individuals search result page, add last_region and last_freeform to individuals table right after last_seen
> 562-563-last_region-and-last_freeform

- src/components/AuthenticatedAppHeader/ActionsPane.jsx
only admin/staff/researcher can see the bulk import button on actions pane
> restrict access right to bulk import

- locale/en.json
- src/pages/match/MatchSighting.jsx
1. add a "CONFIRM NO MATCH" button on sightings matching page
2. if selected annotation/animal has been assigned an individual, this button will be hidden
3. if selected annotation/animal hasn't been assigned individual, when click at the "CONFIRM NO MATCH" button, will create a new individual using this animal
4. "CONFIRM MATCH" button works as usual
> 535 no match confirmation

- locale/en.json
- src/components/Footer.jsx
update the year of copy right to real-time year
> update copyright line

- locale/en.json
- src/pages/sighting/encounters/AnnotationsCard.jsx
on sighting page annotation tab, change the + sigh to a tertiary button with text "ASSIGN"
> change add sign to ASSIGN button

- src/pages/sighting/statusCard/CurationStep.jsx
change photographs to annotations since photographs is not in use anymore
> change photographs to annotations

- src/pages/sighting/CommitBanner.jsx
- src/pages/sighting/SightingCore.jsx
- src/pages/sighting/SightingEntityHeader.jsx
add an ASSIGN button in pending banner on sightings page, when user clicks at it, will navigate to animal tab, where user can assign annotations to animals.
> 571-add-assign-button

- src/hooks/useFetch.js
- src/pages/controlPanel/ControlPanel.jsx
- src/pages/setup/Requests.jsx
1. in useFetch hook, return statusCode directly from useQuery result, avoid state updates after a component has been unmounted.
2. remove some deprecated lines from control panel page
3. remove some unused imports from Requests page
> 516 unmounted component warning

- src/pages/match/ImageButton.jsx
- src/pages/match/ImageCard.jsx
- src/pages/match/MatchCandidatesTable.jsx
- src/pages/match/MatchSighting.jsx
1. add image carousel to match status page
2. image carousel show images that belong to the same individual or encounter
> 610 image carousel

- locale/en.json
- src/components/cards/SightingsCard.jsx
- src/components/dataDisplays/DataDisplay.jsx
- src/constants/queryKeys.js
- src/models/users/useGetUserSightings.js
- src/models/users/useGetUserUnproccessedAssetGroupSightings.js
- src/pages/changeLog/ChangeLog.jsx
- src/pages/dataPage/DataPage.jsx
add paginating to my sightings/my pending sightings/my unapproved sightings
> data page paginating

- src/pages/dataPage/DataPage.jsx
adjust text color and fix a small bug about sightings count
> adjust text color and fix a small bug

- locale/en.json
- src/components/dataDisplays/DataDisplay.jsx
- src/components/dataDisplays/IndividualsDisplay.jsx
deal with response status code 400 and 403 when making requests to download search result on individuals/sightings/encounters page.
if status code is 400 or 403, a dialog will open with messages indicating there is no result to export etc.
> 623 export restricted access

- locale/en.json
- src/components/dataDisplays/DataDisplay.jsx
- src/components/dataDisplays/ElasticsearchEncountersDisplay.jsx
- src/components/dataDisplays/ElasticsearchSightingsDisplay.jsx
- src/components/dataDisplays/IndividualsDisplay.jsx
- src/pages/userManagement/constants/roleSchema.js
- src/utils/roleUtils.js
remove exporter role from UI:
1. user won't be able to create exporter role
2. also remove exporter role on edit users page
3. update the criteria to hide/display download button: now everyone can see the button, any user can possibly download, but with different access right to data.
> remove exporter from UI and optimize code

- src/components/dataDisplays/ElasticsearchEncountersDisplay.jsx
- src/pages/match/ImageCard.jsx
- src/pages/sighting/SightingCore.jsx
1. on animal search page, user can click to navigate to the sighting: animal tab of a given animal.
> 626 animal search page action directing

- src/AuthenticatedSwitch.jsx
- src/components/AuthenticatedAppHeader/ActionsPane.jsx
- src/components/UserProfile.jsx
- src/pages/dataPage/DataPage.jsx
1. make data page the home page
2. add router for user profile component
> 609 part 2

- src/components/EditUserMetadata.jsx
- src/components/UserProfile.jsx
fix the role chip display issue
> fix the role display issue
